export const OPEN_SIDE_BAR = "OPEN_SIDE_BAR";
export const OPEN_FILTER_ORDER = "OPEN_FILTER_ORDER";
export const OPEN_FILTER_MODEL = "OPEN_FILTER_MODEL";
export const OPEN_CATEGORY_MODAL = "OPEN_CATEGORY_MODAL";
export const OPEN_RATE_MODAL = "OPEN_RATE_MODAL";
export const OPEN_ORDER_MODAL = "OPEN_ORDER_MODAL";
