export const FETCH_RATE_TYPE_REQUEST = "FETCH_RATE_TYPE_REQUEST";
export const FETCH_RATE_TYPE_SUCCESS = "FETCH_RATE_TYPE_SUCCESS";
export const FETCH_RATE_TYPE_ERROR = "FETCH_RATE_TYPE_ERROR";
export const CHANGE_RATE_TYPE = "CHANGE_RATE_TYPE";
