export const CHOOSE_DEFAULT_CAR_CARD = "CHOOSE_DEFAULT_CAR_CARD";
export const CHOOSE_CHANGE_CAR_CARD = "CHOOSE_CHANGE_CAR_CARD";
export const EDIT_NAME_CAR = "EDIT_NAME_CAR";
export const DELETE_CAR = "DELETE_CAR";
export const DELETE_CAR_CREATOR = "DELETE_CAR_CREATOR";
