export const CHOOSE_DEFAULT_CAR_CARD = "CHOOSE_DEFAULT_CAR_CARD";
export const CHOOSE_CHANGE_CAR_CARD = "CHOOSE_CHANGE_CAR_CARD";
export const CHANGE_CAR_CATEGORY = "CHANGE_CAR_CATEGORY";
export const CHANGE_CAR_DESCRIPTION = "CHANGE_CAR_DESCRIPTION";
export const CHANGE_CAR_NAME = 'CHANGE_CAR_NAME'