export const GET_STATUS_MODELS = "GET_STATUS_MODELS";
export const GET_STATUS_ORDERS = "GET_STATUS_ORDERS";
export const GET_STATUS_CATEGORY = "GET_STATUS_CATEGORY";
export const GET_STATUS_RATES = "GET_STATUS_RATES";
export const GET_STATUS_RATE_TYPES = "GET_STATUS_RATE_TYPES";
