export const FETCH_REQUEST_STATUS_ORDER = "FETCH_REQUEST_STATUS_ORDER";
export const FETCH_SUCCESS_STATUS_ORDER = "FETCH_SUCCESS_STATUS_ORDER";
export const FETCH_ERROR_STATUS_ORDER = "FETCH_ERROR_STATUS_ORDER";
export const GET_CITY_NAME = " GET_CITY_NAME";
