export const FETCH_RATE_REQUEST = "FETCH_RATE_REQUEST";
export const FETCH_RATE_SUCCESS = "FETCH_RATE_SUCCESS";
export const FETCH_RATE_ERROR = "FETCH_RATE_ERROR";
export const CHANGE_RATE = "CHANGE_RATE";
