export const FETCH_CATEGORY_REQUEST = "FETCH_CATEGORY_REQUEST";
export const FETCH_CATEGORY_SUCCESS = "FETCH_CATEGORY_SUCCESS";
export const FETCH_CATEGORY_ERROR = "FETCH_CATEGORY_ERROR";
export const GET_CATEGORY_NAME = "GET_CATEGORY_NAME";
export const CHANGE_CATEGORY = "CHANGE_CATEGORY";
export const PUT_CATEGORY = "PUT_CATEGORY";
export const POST_CATEGORY = "POST_CATEGORY";
export const DELETE_CATEGORY = "DELETE_CATEGORY";