export const FETCH_MODELS_REQUEST = "FETCH_MODELS_REQUEST";
export const FETCH_MODELS_SUCCESS = "FETCH_MODELS_SUCCESS";
export const FETCH_MODELS_ERROR = "FETCH_MODELS_ERROR";
export const CHOOSE_PAGE_ACTIVE = "CHOOSE_PAGE_ACTIVE";
export const COUNT_MODELS = "COUNT_MODELS";
