export const FETCH_REQUEST_CITIES = "FETCH_REQUEST_CITIES";
export const FETCH_SUCCESS_CITIES = "FETCH_SUCCESS_CITIES";
export const FETCH_ERROR_CITIES = "FETCH_ERROR_CITIES";
export const GET_CITY_NAME = " GET_CITY_NAME";
